"""Pin the externalized prompts. They were generated byte-identical from the original
hardcoded prompts; these hashes catch any accidental drift. Update a hash ONLY with a
reviewed, intentional prompt change (and re-run the eval set)."""
import hashlib
from prompt_config import PROMPTS


def _md5(s):
    return hashlib.md5(s.encode()).hexdigest()


def test_prompts_pinned():
    assert _md5(PROMPTS["system"]) == "e603678c43d47ecac834e04474cd0305"
    assert _md5(PROMPTS["person"]) == "93aab07cad216549a25e56247544b020"
    assert _md5(PROMPTS["screen"]) == "059bf2aeefc3035494902fde3235aa37"


def test_screen_template_substitutes():
    out = PROMPTS["screen"].replace("<W>", "1000").replace("<H>", "563")
    assert out.startswith("Underground mine face, image is 1000x563 px.")
    assert "<W>" not in out and "<H>" not in out
